### ISSUE TITLE
Let's merge this repo into go-community

### ISSUE THREAD

**Issue by Xuanwo** [Prnyself/report-script#1]

**Comment by Prnyself** [comment]
Add a new command directly?

**Comment by Xuanwo** [comment]
> Add a new command directly?

Add into generate directly? We can use the data directly instead of parse generated page.

**Comment by Prnyself** [comment]
`generate` You mean `report cmd`?

**Comment by Xuanwo** [comment]
> `generate` You mean `report cmd`?

Yep.

**Comment by Prnyself** [comment]
1. Shall we ignore events posted by bot?
2. Shall we ignore repos without events?

**Comment by Xuanwo** [comment]
1. Y
2. Y

**Comment by Prnyself** [comment]
Add in https://github.com/beyondstorage/go-community/pull/18

**Comment by Prnyself** [comment]
closed by https://github.com/beyondstorage/go-community/pull/18
